[package]
name = "ruos"
version = "0.0.1"
authors = ["Andrey Golubev <andpgolubev@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0"
volatile = "0.1.0"
spin = "0.4.5"
multiboot2 = "0.1.0"